---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: comunikDashboard
  label: comunikDashboard
  create: all
  match: "**/*"
- type: directory
  path: comunikTelecom
  label: comunikTelecom
  create: all
  match: "**/*"
- type: directory
  path: comunikContact
  label: comunikContact
  create: all
  match: "**/*"
- type: document
  path: README.md
  label: Homepage
  match: "**/*"
- type: directory
  path: comunikSales
  label: comunikSales
  create: all
  match: README.md
- type: directory
  path: comunikVoip
  label: comunikVoip
  create: all
  match: README.md
- type: directory
  path: comunikCRM
  label: comunikCRM
  create: all
  match: README.md
upload_dir: public
public_path: "/public"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run site:develop
